### ISSUE TITLE
obuild cannot parse findlib predicates

### ISSUE THREAD

**Issue by yallop** [ocaml-obuild/obuild#126]
For example, the [ctypes META file](https://github.com/ocamllabs/ocaml-ctypes/blob/397e9c4757f6647b2530d8908d8fec2e571c2ad5/META#L36) has the following:

```
requires(-mt) = "ctypes.foreign.unthreaded"
```

which causes [netlink](https://github.com/xapi-project/ocaml-netlink) (which depends on ctypes) to fail with a parse error:

```
error: unexpected parse error 'expecting '+=' or '=' after requires' in meta file /home/jeremy/.opam/4.01.0/lib/ctypes/META
```

**Comment by jeromemaloberti** [comment]
Thank you for the report.
There are actually 2 problems/bugs. 
The first is that negative predicates (-mt) cannot be parsed in the current version of obuild (I just fixed it on my dev branch). The second is that negative predicates are not checked (I'm working on it now). 
Hopefully, I will push a fix soon.

**Comment by UnixJunkie** [comment]
related to
https://github.com/ocaml-obuild/obuild/issues/121

**Comment by UnixJunkie** [comment]
Thanks for trying to fix this.
I can test the fix if needed, just tell me.

**Comment by jeromemaloberti** [comment]
I pushed a fix on master.
That would be very useful if you could test.

**Comment by UnixJunkie** [comment]
I did tests on my side: obuild can now parse the META file from ocamlnet's rpc library.
Maybe @yallop can test his case again against the current master branch of obuild.

**Comment by yallop** [comment]
Unfortunately, the master obuild branch still can't parse my [META file](https://github.com/ocamllabs/ocaml-ctypes/blob/397e9c4757f6647b2530d8908d8fec2e571c2ad5/META#L36).  Here's how to reproduce the failing netlink build:

```
$ opam switch 4.02.1
[...]
$ eval `opam config env`
$ opam pin add obuild git@github.com:ocaml-obuild/obuild.git 
[...]
$ opam install ctypes.0.4.0
[...]
$ git clone git@github.com:xapi-project/ocaml-netlink.git
$ cd ocaml-netlink
$ obuild configure
Configuring ocaml-libnl-0.1...
error: unexpected parse error 'expecting '+=' or '=' after requires' in meta file /home/jeremy/.opam/4.02.1/lib/ctypes/META
```

**Comment by jeromemaloberti** [comment]
Indeed, I didn't notice it was on the "require" keyword. I need to do more work.

**Comment by UnixJunkie** [comment]
@yallop there is no obuild file in ocaml-netlink
I cannot reproduce your recipe

**Comment by UnixJunkie** [comment]
@jmaloberti do you support the require keyword?

**Comment by yallop** [comment]
> @yallop there is no obuild file in ocaml-netlink
> I cannot reproduce your recipe

You can reproduce it by checking out a [revision](https://github.com/xapi-project/ocaml-netlink/tree/86356f6e6fd85e3a9aeba21916af3d8afbbd9b1e) which still contained an obuild file:

```bash
git checkout 86356f6e
```

**Comment by jeromemaloberti** [comment]
Yes, but not with predicate. I fixed the parsing, so it will not raise the exception anymore, however, the compilation DAG cannot choose the right sub  package yet, I need to fix it.
